server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall
    username: root
    password: admin
  application:
    name: mybatis-plus-learn
logging:
  level:
    com.liuhongyin.mybatispluslearn.mapper: TRACE
